export const SNIPS = [
  { id:"js-fetch",    lang:"javascript", title:"Fetch JSON",          desc:"Safe async fetch with error handling.",          tags:["fetch","async"],    code:`async function getData(url) {\n  try {\n    const res = await fetch(url);\n    if (!res.ok) throw new Error(\`HTTP \${res.status}\`);\n    return await res.json();\n  } catch (err) { console.error(err); return null; }\n}` },
  { id:"js-debounce", lang:"javascript", title:"Debounce",            desc:"Delay fn until burst of calls ends.",            tags:["performance"],       code:`function debounce(fn, delay=300) {\n  let t;\n  return (...args) => { clearTimeout(t); t = setTimeout(()=>fn(...args), delay); };\n}` },
  { id:"js-deepclone",lang:"javascript", title:"Deep Clone",          desc:"Recursively clone objects & arrays.",            tags:["objects"],           code:`function deepClone(obj) {\n  if (obj===null||typeof obj!=='object') return obj;\n  if (Array.isArray(obj)) return obj.map(deepClone);\n  return Object.fromEntries(Object.entries(obj).map(([k,v])=>[k,deepClone(v)]));\n}` },
  { id:"js-sleep",    lang:"javascript", title:"Sleep",               desc:"Promise-based async delay.",                    tags:["async"],             code:`const sleep = (ms) => new Promise(r => setTimeout(r, ms));\nawait sleep(1000);` },
  { id:"ts-fetch",    lang:"typescript", title:"Typed Fetch",         desc:"Generic fetch with full TS inference.",          tags:["fetch","generics"],  code:`async function fetchData<T>(url: string): Promise<T|null> {\n  try {\n    const res = await fetch(url);\n    return await res.json() as T;\n  } catch { return null; }\n}` },
  { id:"ts-result",   lang:"typescript", title:"Result Type",         desc:"Railway-oriented error handling.",               tags:["types"],             code:`type Result<T,E=Error> = {ok:true;data:T}|{ok:false;error:E};\nasync function safe<T>(fn:()=>Promise<T>):Promise<Result<T>> {\n  try { return {ok:true,data:await fn()}; }\n  catch(e) { return {ok:false,error:e as Error}; }\n}` },
  { id:"r-usefetch",  lang:"react",      title:"useFetch Hook",       desc:"Data fetching with loading & error states.",     tags:["hooks","async"],    code:`function useFetch(url) {\n  const [data,setData]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(null);\n  useEffect(()=>{\n    let c=false;\n    fetch(url).then(r=>r.json()).then(d=>{if(!c)setData(d)}).catch(e=>{if(!c)setError(e.message)}).finally(()=>{if(!c)setLoading(false)});\n    return()=>{c=true;};\n  },[url]);\n  return {data,loading,error};\n}` },
  { id:"r-uselocal",  lang:"react",      title:"useLocalStorage",     desc:"useState that persists across refreshes.",       tags:["hooks","storage"],  code:`function useLocalStorage(key, initial) {\n  const [val,setVal]=useState(()=>{ try{return JSON.parse(localStorage.getItem(key)||'')}catch{return initial} });\n  const set=v=>{ setVal(v); localStorage.setItem(key,JSON.stringify(v)); };\n  return [val,set];\n}` },
  { id:"py-retry",    lang:"python",     title:"Retry Decorator",     desc:"Auto-retry on failure with back-off.",           tags:["utilities"],         code:`import time, functools\ndef retry(times=3, delay=1.0):\n    def dec(fn):\n        @functools.wraps(fn)\n        def wrap(*a,**k):\n            for i in range(1,times+1):\n                try: return fn(*a,**k)\n                except:\n                    if i==times: raise\n                    time.sleep(delay*i)\n        return wrap\n    return dec` },
  { id:"py-timer",    lang:"python",     title:"Timer Context",       desc:"Measure how long any block takes.",              tags:["performance"],       code:`import time\nfrom contextlib import contextmanager\n@contextmanager\ndef timer(label=''):\n    s=time.perf_counter()\n    try: yield\n    finally: print(f'{label}: {(time.perf_counter()-s)*1000:.1f}ms')` },
  { id:"sql-running", lang:"sql",        title:"Running Total",       desc:"Cumulative sum with a window function.",         tags:["window","analytics"],code:`SELECT date, amount,\n  SUM(amount) OVER (ORDER BY date ROWS UNBOUNDED PRECEDING) AS running_total\nFROM transactions ORDER BY date;` },
  { id:"sql-dedup",   lang:"sql",        title:"Deduplicate",         desc:"Keep only the latest row per key.",              tags:["CTE","dedup"],       code:`WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY email ORDER BY created_at DESC) AS rn\n  FROM users\n)\nSELECT * FROM ranked WHERE rn = 1;` },
];

export const LANG_META = {
  javascript:{ color:"#f7df1e", label:"JS"  },
  typescript:{ color:"#60a5fa", label:"TS"  },
  react:     { color:"#61dafb", label:"JSX" },
  python:    { color:"#4ade80", label:"PY"  },
  sql:       { color:"#a78bfa", label:"SQL" },
};